### ISSUE TITLE
Create Summary CSV of Inputs used on model generation

### ISSUE THREAD

**Issue by ghop02** [covid-projections/covid-data-model#100]
It's sometimes unclear:
a) why a specific county doesn't have data
b) where the numbers shown come from
c) what initial values are

I think it would be very helpful to have a csv generated (and presumably shared somewhere, could be a google sheet that is updated?) when model generation runs.

Can have individual state and county summary csvs:

State level:

Latest Date | Country | State | population | beds | cases | deaths | model results generated | case data source 
-----|---------|-------|------------|------|-------|--------|-------------------------|---|
| 2020-04-01 | USA | MA  | 10003 | 1200 | 1000 | 122 | True | JHU

County level:

Latest Date | Country | State | fips | name | population | beds | cases | deaths | model results generated | cases data source 
-----|---------|-------|-----|------|----------|------|-------|--------|-------------------------|---|
| 2020-04-01 | USA | MA | 12345 | Suffolk | 10003 | 1200 | 1000 | 122 | True | JHU

I think this can be done by modifying run.py and keeping track of the results as it run

**Comment by jredding** [comment]
Does it need to be ran at file generation time or could it be a script that summarizes the deployed files?  They should always be the same, but if it summarizes what is deployed/generated that it can act as a cross-check.

**Comment by ghop02** [comment]
Oh that's a good question.

So the disadvantage of running on only the generated files is that it doesn't include the null cases. If a county isn't included, you won't be able to see why (was it because of missing beds, or didn't have case data, etc.)

Also, a lot of times the results in the model files don't have the exact same numbers as what was fed into the model.  For example, beds are scaled down by a factor to account for utilization.

I think the use case you're describing might be slightly different than this (or is just a couple more columns on this report)

**Comment by jredding** [comment]
fair point on the null columns - I think either is appropriate and also works well as a test. If we don't get this done by tomorrow I might make it my Saturday afternoon task ;).

**Comment by davidstrauss** [comment]
It should be really easy to add this, but I'd almost prefer having tractability to the commit hashes for both the model and the source data for published models. Basically, take a card from deterministic builds in the software world.

**Comment by ghop02** [comment]
Can you expand on that a bit @davidstrauss ? If I'm understanding correctly, that seems like it's solving a separate problem - determinism vs observability
