### ISSUE TITLE
Make built_dod_dataset.py not read CSVs (poorly) directly.  Use JHUDataset -> Timeseries dataset

### ISSUE THREAD

**Issue by igorkofman** [covid-projections/covid-data-model#110]
As is, it's fragile to what date it is vs what date the latest dataset is from and likely other issues

**Comment by mikelehen** [comment]
This broke another automation run:  https://github.com/covid-projections/covid-data-model/actions/runs/80276073

Can we get a fix (even if it's hacky) in soooooon?

**Comment by mikelehen** [comment]
Fixed by #254.
