### ISSUE TITLE
JHUDataset load fails in demo Jupyter Notebook (Binder): seird_notebook_runtime.ipynb

### ISSUE THREAD

**Issue by cshewmake2** [covid-projections/covid-data-model#118]
On the main page of the repo (README.md), there is a link to a Binder Jupyter Notebook instance. 
In particular, `seird_notebook_runtime.ipynb` fails on the fourth cell. It's an issue with the `JHUDataset.local()` call. 

![image](https://user-images.githubusercontent.com/11378439/78508889-d5b8c800-774f-11ea-8698-e35e50bde6f1.png)

![image](https://user-images.githubusercontent.com/11378439/78508920-ff71ef00-774f-11ea-97bf-a082308688f3.png)

**Comment by ghop02** [comment]
Hi @cshewmake2 . Thanks for letting us know. Can you clone the `covid-data-public` repo? If the `covid-data-public` and `covid-data-model` repositories are at the same directory level:

```
dir/
   covid-data-model/
   covid-data-public/
```

it should work.

Sorry about that, will figure out a better solution for that issue

**Comment by cshewmake2** [comment]
Thanks for the prompt response @ghop02 . 
I'll give it a shot!

**Comment by davidstrauss** [comment]
If this is still a problem for you, please reopen this. For now, I'll close this.
