### ISSUE TITLE
Write scheduled GitHub Action to run run.sh and deploy to S3.

### ISSUE THREAD

**Issue by mikelehen** [covid-projections/covid-data-model#126]
The goal is to create a scheduled GitHub Action that re-runs our models to generate new API artifacts, and publishes them on data.covidactnow.org ~once daily.

It will need to:
1. clone the covid-data-public repo (will git lfs be an issue?)
2. run `run.sh` (see https://github.com/covid-projections/covid-data-model/issues/123).
3. Publish to S3 according to URL format / version schema specified in https://docs.google.com/document/d/1VhQqMxtVYHQMIj9zFeb1DUQZ1aq1k4xIc_bYoTIqUb4/edit

Notes:
* There's some s3 python code [here](https://github.com/covid-projections/covid-data-model/blob/f1b790585fadf19d34c5176440ca895cb59dfaee/deploy_dod_dataset.py#L8) that might be useful. Or maybe there's a command-line tool that would be easier / better.
* We need to generate a snapshot-id to stick in the ultimate S3 destination.  This could be a precise timestamp or maybe github actions have a unique job ID we could use, or something.

**Comment by mikelehen** [comment]
@goldblatt pointed out that we should use multi-part upload (https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3.html#multipartupload) since the shape files are large and can time out on slow internet connections.

**Comment by fridiculous** [comment]
Also, please note there is a placeholder for this job here: https://github.com/covid-projections/covid-data-model/blob/master/.github/workflows/schedule.yml

**Comment by kpinc** [comment]
I am not clear if this is the right place, but you may want to re-open this issue.  If you look at a state/county at covidactnow.org, the last-updated date is April 6.  This leads me to believe that the data hasn't been pushed since then, which is about when this task was started.

**Comment by fridiculous** [comment]
yes @kpinc - thanks for noting.  the larger goal of model integration has yet to be streamlined to the site.

**Comment by mikelehen** [comment]
This is done.  We're pushing new API snapshots to S3 twice a day, though it's still manual to get them onto the website (and that's slightly blocked by model integration work).
