### ISSUE TITLE
Enable CORS on data.covidactnow.org

### ISSUE THREAD

**Issue by mikelehen** [covid-projections/covid-data-model#131]
Test page to demonstrate it fails: https://mike-stuff.web.app/test-data.html

Result (in JS Console):
> Access to fetch at 'https://data.covidactnow.org/states.csv' from origin 'https://mike-stuff.web.app' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

We need to get CORS working, which probably means adding a `Access-Control-Allow-Origin: *` header.  

Note that in a past lifetime I recall `*` had limitations and it ended up being better to instead set the header to whatever the incoming requests `Origin` was set to.  If we do that, we also probably need to set `Vary: Origin` to avoid unwanted caching by proxies, etc.  We should probably start with just setting it to `*`.

**Comment by fridiculous** [comment]
@mikelehen  - i think this works! 

https://mike-stuff.web.app/test-data.html

![image](https://user-images.githubusercontent.com/1227514/78629667-8c9a6e00-784c-11ea-8766-097f5642580a.png)

**Comment by mikelehen** [comment]
Yes!  Thank you!

**Comment by mikelehen** [comment]
For some reason, this has regressed.  So this will block moving the website over to snapshots. 😦

**Comment by fridiculous** [comment]
works again
