### ISSUE TITLE
Change model schema format.

### ISSUE THREAD

**Issue by mikelehen** [covid-projections/covid-data-model#144]
Currently we spit out 4 model files per state/county, each representing a different intervention. And while the file is JSON, it's really just arrays of columns.  We want to move instead towards a single JSON file per state/county that looks something like:
```
{
  "modeledInterventions": {
    "limited_action": {
      "hospitalizations": 123,
      "beds": 123,
      "deaths": 123,
      "infected": 123,
      "totalPopulation": 123,
      "date": 123,
      "daysOut": 123
    },
    ...other interventions
  }
  "lastUpdated": datetime
}
```

The exact fields and names need a bit of vetting and maybe we want to merge in some additional summary info.  But somebody can start figuring out what this code change would look like.

Also, I'm not sure how the code is structured, but if it's difficult to make this sort of change we should try to move the code in a direction such that it's easier (we should separate "API output" from our model internals, etc.  @fridiculous may have specific ideas on what this should look like.)

**Comment by igorkofman** [comment]
We should have a "current" field which gives us the current intervention's model (or otherwise include that info here).  This means run.py needs access to interventions, which would need to live in model-data-public.

**Comment by BrettBoval** [comment]
The spirit of these changes lives on, but the implementations recommended here are extremely stale.
