### ISSUE TITLE
Deep Clean & Re-Structure of Repo

### ISSUE THREAD

**Issue by fridiculous** [covid-projections/covid-data-model#145]
As suggested from the [data api doc]( https://docs.google.com/document/d/1VhQqMxtVYHQMIj9zFeb1DUQZ1aq1k4xIc_bYoTIqUb4/edit?ts=5e8a3a1e#) we need a separation of concerns between different parts of the application.

In general, the repo structure should treat the following implementations independently:
1) How datasets get defined, loaded, and sanitized - `libs/datasets/sources`
2) How datasets get defined as a canonical source for that type of data - `libs/datasets/models`
3) How functions and general transformations are defined - `libs/functions/transforms`
4) How statistical functions are defined `libs/functions/models`
5) How pipelines are defined as steps for functions and dataset steps - `libs/pipelines`
6) How the resultant API schema is defined and written to - `api`
7) How the pipelines are triggered - `cli`
8) How triggerable pipelines are automated - `.github/workflows/`
9) Where notebooks & exploratory analyses are kept - `analyses`

As a result, I propose we use the following structure to more cleanly separate the varying responsibilities needed within this repo.
```bash
├── .github/workflows
├── analyses
├── api
├── cli
├── libs
│   ├── datasets
│   │   ├── sources
│   │   └── api
│   └── models
│   │   ├── ensemble
│   │   ├── inference
│   │   └── seir
│   └── pipelines
└── tests
    ├── data
    └── results
```

Much of this work would require moving the existing repo to match this structure, including moving some functions around to live in their target homes.

EDIT:  Taking in notes and updating the hierarchy above

**Comment by ghop02** [comment]
Couple questions/comments:
 - `functions` feels a bit broad do we need this structure? 
 - I'm a bit leery of separating "transforms" away from data sources/data models. I'm just not 100% sure what I expect to live there.
 - Why are models in functions? If i'm looking at `libs/` without knowing anything, seeing `datasets` and `models` at the top level feels clearer than models living in functions. 
 - What goes in `dataset/models`? the word model will always be overloaded in a project that involves actual models :P.

In general I liked the flatter structure a bit more, to me the data structures that will define these matter a bit more than the folder structure, and I don't quite have a handle on that. 

It might be helpful for someone to do a quick run through of applying this structure (or other) to the dod "pipeline" as a draft PR to see a bit more concretely how those changes manifest/what feels right.

**Comment by BrettBoval** [comment]
done
