### ISSUE TITLE
Be able to set Redirect Rules on S3 to specific folders

### ISSUE THREAD

**Issue by fridiculous** [covid-projections/covid-data-model#146]
We need to have data.covidactnow.org needs to have a `latest` and `stable` "symlinks" to specific snapshots of data that live at `data.covidactnow.org/v0/<snapshotid>/...`.  

Such that both`data.covidactnow.org/v0/latest` and `data.covidactnow.org/v0/stable` point to specific snapshot ids.

`latest` is for the most recent snapshot
`stable` is for what data we designate as the 'production' version

And the process to update or change these ids should be formalized preferably in a shell script.

Possible context for how to make this work:
https://docs.aws.amazon.com/AmazonS3/latest/dev/how-to-page-redirect.html

**Comment by mikelehen** [comment]
FWIW- In the interest of pretty URLs, I wonder if it's worth trying to set up the redirect so `stable` is the default and doesn't need to appear in the URL.

Something like:
* `https://data.covidactnow.org/v0/snap/<snapshot-id>/...endpoint.json`
* `https://data.covidactnow.org/v0/snap/latest/...endpoint.json`
* `https://data.covidactnow.org/v0/...endpoint.json` (stable)

If that's hard we could do:
* `https://data.covidactnow.org/v0-snap/<snapshot-id>/...endpoint.json`
* `https://data.covidactnow.org/v0-snap/latest/...endpoint.json`
* `https://data.covidactnow.org/v0/...endpoint.json` (stable)

**Comment by raygilbert** [comment]
Quick tests on S3 console shows this will work.

**Comment by fridiculous** [comment]
@raygilbert do you have code snippet or a script to make this work?

**Comment by raygilbert** [comment]
I'll push something tonight that has my WIP

**Comment by raygilbert** [comment]
Pushed symlinks.sh which operates at a folder level rather than a file by file level.  Should be easier to run with limited/no interruption to users pulling data

**Comment by igorkofman** [comment]
Is this still WIP?

**Comment by raygilbert** [comment]
The work is pushed and done.

**Comment by raygilbert** [comment]
Looking at how to do this with AWS API Gateway.
