### ISSUE TITLE
Clean up STDOUT and STDERR pollution.

### ISSUE THREAD

**Issue by mikelehen** [covid-projections/covid-data-model#148]
I'm wrapping our run_model.py / run_data.py scripts in a bash run.sh script and right now we spit out so much garbage to STDOUT and STDERR that I need to redirect it to /dev/null. 😱 

We need to (at least have a mode we can optionally enable that):
1. Doesn't spit out anything to STDOUT if everything is successful.
2. Doesn't spit out anything to STDERR unless there is an issue that needs human investigation.

For 2, we currently get messages like:
> WARNING:libs.datasets.dataset_utils:Did not match 52 codes to county data.
WARNING:libs.datasets.dataset_utils:['00066', '00072', '00078', '60000', '66000', '69000', '78000', '80008', '80015', '80040', '88888', '90001', '90002', '90004', '90005', '90006', '90008', '90009', '90010', '90012', '90013', '90015', '90016', '90017', '90019', '90020', '90021', '90023', '90024', '90025', '90027', '90029', '90030', '90031', '90032', '90033', '90034', '90035', '90036', '90038', '90039', '90040', '90044', '90046', '90047', '90049', '90050', '90051', '90053', '90054', '90055', '99999']

I don't know what this means and if it's important.  We may need to audit these and start having a list of whitelisted data abnormalities that we are intentionally ignoring for now.  And then if there are new / different abnormalities, the script should probably log details to STDERR and exit with a non-zero exit code.

**Comment by BrettBoval** [comment]
This is still an issue :)
