### ISSUE TITLE
Clean up webui_data_adaptor_v1 FIPS handling for states

### ISSUE THREAD

**Issue by davidstrauss** [covid-projections/covid-data-model#165]
Currently, we check the FIPS code length and fall back to the state code in an object attribute. We can do better.

One option is implementing #162, but @erccarls proposed a more direct option:

> the `us` package is really nice. us.states.lookup().fips
> The lookup string can be fips code, abbrv, full name etc.. and lower case etc..
> .abbr
> .name give the other attrs

Either way, we should replace the current behavior.

**Comment by BrettBoval** [comment]
done
