### ISSUE TITLE
Named Keys JSON States and Counties 

### ISSUE THREAD

**Issue by fridiculous** [covid-projections/covid-data-model#168]
We need to switch state and counties data from array of arrays to named keys JSON.

For the first pass of this change, please attempt this structure:
```json
[
        {
        "day_index":0,
        "date": "3/8/20",
        "all_hospitalized": 5239,
        "all_infected": 14178,
        "dead": 226156,
        "beds": 57069,
        "population": 21477737
        }, 
        {
...
        }
]
```

Preferably, the files are written by the generic api writer outlined here:
https://github.com/covid-projections/covid-data-model/issues/167

Also, as a result of making this change, please update the api docs https://github.com/covid-projections/covid-data-model/blob/master/api/README.md#arrays

**Comment by ghop02** [comment]
It would be really cool to have a typed record in between the dataframe and the output so we can better control what's being output (that class can generate a json-schema output as well)

https://github.com/covid-projections/covid-data-model/pull/159/files#diff-79261b301b90ef653107a195b4f53ef0R19-R32
