### ISSUE TITLE
Duplicate date entries for intervention scenarios

### ISSUE THREAD

**Issue by jeremiahwander** [covid-projections/covid-data-model#179]
Just starting to work with the codebase, so I apologize if this has been previously discussed, but in CovidTimeSeriesModelSIR->run_interventions it looks like there's a potential indexing issue where the post-intervention projections in `new_df` get appended to the pre-intervention subset of `combined_results` (termed `early_combo_df`).

The lines of interest are as follows:

`new_df = dataframe_ify(data, date, end_date, steps,)`
`early_combo_df = combined_df.copy().loc[:date]`
`combined_df = early_combo_df.append(new_df, sort=True)` 

Because of a subtlety in indexing for a DatetimeIndex, indexing using `.loc[:date]` includes all rows up to **and including** the row indexed by date. `new_df` also includes a row for that date such that when appending `new_df` to `early_combo_df` one ends up with two rows in `combined_df` with an index of `date` and `combined_df.index.is_unique` is no longer true.

This is hidden by the fact that `run.prepare_data_for_website` currently has an interval of 4, so the dates once again become unique.

This is possibly the root cause for https://github.com/covid-projections/covid-data-model/issues/140 because when dropping all but every 4th row, duplicate dates would lead to shorter time intervals between retained rows.

**Comment by davidstrauss** [comment]
I suspect this isn't applicable any longer given the replacement of the modeling implementation, but I don't want to close this on presumption.

**Comment by BrettBoval** [comment]
Months later. Officially closing this on presumption.
