### ISSUE TITLE
data.covidactnow.org should serve 404 instead of 403 w/ xml junk for wrong endpoints.

### ISSUE THREAD

**Issue by mikelehen** [covid-projections/covid-data-model#180]
Go to http://data.covidactnow.org/broken.json

You get a 403 response:
```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>0A8EA62331716809</RequestId>
<HostId>
iFxeRDpbJiGy61kIolJoYXFkachnzCtYo7BKSytnYOhJZwT/5i1M5q8aBosnY4kqvZc3yD89pDI=
</HostId>
</Error>
```

It should ideally be a 404 page instead.

@fridiculous @igorkofman This isn't high-pri, but it could be confusing once we have folks poking at API endpoints.

**Comment by mikelehen** [comment]
FWIW- It would be really nice to fix this pretty quick now that the API is published.  Serving 403 is fundamentally wrong and could easily confuse people trying to use the API (they think it's a permission issue rather than just them typoing an endpoint).

I'd also kind of like the website to be able to differentiate "this data doesn't exist" from other errors.

**Comment by BrettBoval** [comment]
@mikelehen I assume this was fixed. Can I close this?

**Comment by mikelehen** [comment]
It was not, but it is now! 😁
