### ISSUE TITLE
Generate schema for existing county summary data pipeline with tests

### ISSUE THREAD

**Issue by ghop02** [covid-projections/covid-data-model#185]
This is for generating a schema flow for outputting county summary data.
It can take some ideas from [this pr](https://github.com/covid-projections/covid-data-model/pull/159/files).

 - Independent python file containing only the pydantic object for outputting data.
 - command (preferably in the cli) to generate all schemas and save them as json-schema formats.
 - pipeline file to take dataframes and write output data in the expected schema

**Comment by BrettBoval** [comment]
Can we close @ghop02?
