### ISSUE TITLE
Add Bottleneck to requirements.txt, fix any related issues

### ISSUE THREAD

**Issue by davidstrauss** [covid-projections/covid-data-model#195]
Pandas opportunistically uses Bottleneck when available to accelerate math operations instead of using numpy. While I haven't benchmarked overall impacts, the effects seem to be substantial for anything that would otherwise run through numpy based on what I've read. Bottleneck does appear to be slightly different in implementation for some computations, but it should rarely manifest as an actual difference on 64-bit systems (but is reportedly pronounced on 32-bit systems).

Also, if we don't add it, we risk it getting picked up anyway if it happens to be on a computer, causing some extremely obscure type issues that are easy to avoid if we just install Bottleneck. It also appears to be the case that code compatible _with_ Bottleneck present works fine _without_ Bottleneck, too. So, developing with Bottleneck appears to be the fast, safer choice.

Additional background: https://stackoverflow.com/questions/53042250/mean-from-pandas-and-numpy-differ

**Comment by BrettBoval** [comment]
Closing because it's quite stale. We can revive if we want to bring this back on the trello board.
