### ISSUE TITLE
Reorganize data sources to ensure consistent data cleaning

### ISSUE THREAD

**Issue by ghop02** [covid-projections/covid-data-model#199]
One of the difficulties we have with the current structure is that there are no common assumptions we can make about data sources and as a result, we have hacked together solutions throughout the code base.

I think that there are a handful of issues that make this difficult, I'd like to enumerate them to figure out the best way to handle them:
#### Column names differ across different data sources:

We use "country" in some places, but in others that column name may be "Country/Region"

#### Not all data has fips codes

We add in fips data in the middle of processing in some places.  We should make sure that any data frame we are using to combine data has a fips column for county and state level data.

#### Missing Data is Represented in different ways

In some datasets we'll assign an unknown fips "99999", in other datasets we'll drop the missing data.  This data should be properly categorized consistently across datasets so we can reason about it.

#### State and Country values are not consistently represented

In a field called "country" sometimes that value is the full name "United States" and other times it's "USA".  Same with state, sometimes its "massachusetts" other times it's "MA"

#### Common descriptive data exists in multiple different forms

For instance, we surface latitude/longitude in some places, but we don't have a high level object we can work with that has all.  In eric's branch, he has a metadata object that provides a lot of this information.  We should have a high level object that has: "country, county, state, fips, population, lat/long,intervention, maybe beds data"

#### Data is loaded opportunistically instead of passed in to processing functions

In a lot of areas, we load the data in as it's needed as opposed to passing already loaded data in:

for example in build_dod_dataset:
```
def get_usa_by_states_df(input_dir, intervention_type):

    us_only = _get_usa_by_county_df()
    abbrev_df = _get_abbrev_df()
    interventions_df = _get_interventions_df()
    projections_df = get_state_projections_df(
        input_dir, intervention_type, interventions_df
    )
```
would be more clear and easy to work with if all the data was loaded before that function:

```
def get_usa_by_states_df(intervention, latest_us_case_data: pd.DataFrame, projections_df: pd.DataFrame):
    ...
```
This makes testing the functionality in `get_usa_by_states_df` possible.

**Comment by ghop02** [comment]
Here's a first pass at a way that might help solve some of these issues:
https://github.com/covid-projections/covid-data-model/pull/200

 - Adding "common fields" that are shared for all data and apply common preprocessing
 - Putting more logic into data sources

I think it's a start, but it doesn't quite address combining sources or backfilling missing data.

**Comment by BrettBoval** [comment]
@ghop02 can we close this now?
