### ISSUE TITLE
[API] Create Model Staging Process via Slack Notification

### ISSUE THREAD

**Issue by fridiculous** [covid-projections/covid-data-model#218]
After the model json outputs are pushed to s3, we need a method to compare 2 different snapshots as a part of staging the model.

To help stage the model, we should notify users in a slack channel about a new model snapshot being ready, so that people can review the model right before the data becomes live.

The contents of the message should have:
* the snapshot location of the model output
* a link to compare on prod covid-projections with the new model ouput to the current model output
* The slack channel should be called #model-staging.

Once reviewed, someone can make the call that the model is ready for consumption, and trigger the label action

Labeling the model should also notify slack that the model has been updated so that everyone is aware a new model is running on the site.

Here's a sample github action used with slack notification.
https://github.com/marketplace/actions/slack-notify

**Comment by BrettBoval** [comment]
Implemented.
