### ISSUE TITLE
Improve Performance via Parallelization

### ISSUE THREAD

**Issue by fridiculous** [covid-projections/covid-data-model#225]
Currently, we only have some jobs parallelized.  We have a machine with 16 cores, but most of the time only 1 core is being used.

These the current processes in run.sh that ahve been parallelized:
- [x] state models 
- [x] county models 
- [ ] county-summary 
- [ ] case summaries
- [ ] deploy-dod
- [ ] deploy-top-counties 
- [ ] deploy-states-api
- [ ] deploy-counties-api

**Comment by BrettBoval** [comment]
Closing due to staleness. A lot of work was put into this, and we happily distribute to all the cores in the self-hosted runner.
