### ISSUE TITLE
Standardize Code Formatting

### ISSUE THREAD

**Issue by ghop02** [covid-projections/covid-data-model#230]
Now that most of the large epics are in master, i'd love to get an auto-formatter setup. 

Steps that have to happen:
 - [ ] run black on repo `make fmt` or `black .`
 - [ ] Add instructions for how to easily add black formatting as a pre-commit hook
 - [ ] Add linting to make sure that committed code is properly formatted: [Github action linter](https://github.com/marketplace/actions/black-code-formatter)

**Comment by BrettBoval** [comment]
black now runs as a pre-commit hook
