### ISSUE TITLE
Collect All PySEIR output in snapshots

### ISSUE THREAD

**Issue by erccarls** [covid-projections/covid-data-model#247]
Currently only `output/web_ui` is shipped to the snapshots. 

For QA purposes and additional introspection, we would like to also collect pyseir output reports and data.  

Specifically a zip of the state_summaries folder is ideal as is a concatenation of all PDF files in that folder to a single PDF that can be used for rapid QA.

**Comment by mikelehen** [comment]
I kicked off https://github.com/covid-projections/covid-data-model/actions/runs/80176747 which should generate a snapshot with a pyseir_state_summaries.zip file in it.  Will update here once it's finished.

I'll look into generating the concatenated PDF separately.
