### ISSUE TITLE
Create Batch versions of API data

### ISSUE THREAD

**Issue by ghop02** [covid-projections/covid-data-model#268]
Right now, the API reports per state and per county data, separated out into individual files.
`/latest/us/states/` and `/latest/us/counties/` . 
We don't yet have this data aggregated into batch versions of this data:

 - /latest/us/states(.intervention).json
 - /latest/us/states(.intervention).timeseries.json
 - /latest/us/counties(.intervention).json
 - /latest/us/counties(.intervention).timeseries.json

This will mostly be a rollup of what we currently have.

**Comment by ghop02** [comment]
couple questions - do we want to surface just the raw data anwywhere without a specific intervention?

Also a quick proposed schema change:
```diff
- /latest/us/states(.intervention).json
- /latest/us/states(.intervention).timeseries.json
+ /latest/us/states.summary(.intervention).json
+ /latest/us/states.timeseries(.intervention).json
+ /latest/us/states(.intervention).json
```
the idea being that `states(.intervention).json` has all timeseries and summary data

**Comment by igorkofman** [comment]
1. Define "raw data"?
2. Let's stick to current schema to start

**Comment by ghop02** [comment]
Oh, sorry, `actuals` would've been the better term.

And sounds good.
