### ISSUE TITLE
Add R_t regressions for county interventions data.

### ISSUE THREAD

**Issue by erccarls** [covid-projections/covid-data-model#272]
#271 Adds state and county level inference for R_t. This issue seeks to extend this by taking "public implementation data" which describes time series for each county's mitigation policy, and matching this to R_t suppression. 

Specifically we would like to understand, how well a given policy helped to drive R_t_after_implemenation / R_t_before_implementation.  

There is likely lag structure that needs to be accounted for, likely that standard signal processing techniques will be valuable here.

Example usage of R_t codes until pipeline integration has completed.

```
import us
from pyseir.inference.infer_rt import RtInferenceEngine

engine = RtInferenceEngine(
    fips='06037', # us.states.lookup('06').fips,
)

df = engine.infer_all(plot=True, shift_deaths=0)
```

County level implementation data can be found in `load_data.load_public_implementations`.  There may be better data sources, especially at state level which is not included in the above.

**Comment by BrettBoval** [comment]
No longer in scope.
