### ISSUE TITLE
Expose inferred and "indicator" historical Rt values through the API timeseries

### ISSUE THREAD

**Issue by igorkofman** [covid-projections/covid-data-model#309]
Indicator Rt is being added to model output here:
https://github.com/covid-projections/covid-data-model/pull/308/files

Inferred Rt is already in the output (but as a single static value) - it will become variable and available historically.  We currently grab the the static value and put it in the "projections" JS dict in the API, not in the timeseries
See libs/datasets/can_model_output_schema.py 

We want both to be exposed (along with the confidence intervals) in the timeseries.

A reference change for expose new columns in the timeseries
https://github.com/covid-projections/covid-data-model/pull/307/files

**Comment by igorkofman** [comment]
Per changes in https://github.com/covid-projections/covid-data-model/pull/308/files maybe we shouldn't put the CI confidence level in the field name as it seems we're playing around with that..

**Comment by davidstrauss** [comment]
> Per changes in https://github.com/covid-projections/covid-data-model/pull/308/files maybe we shouldn't put the CI confidence level in the field name as it seems we're playing around with that..

I wasn't 100% sure how to approach that, but I included it for now because `RtCI90` was already established as a field name. Happy to do a follow-up if it needs to change.

**Comment by davidstrauss** [comment]
For my PR:
> Are the api docs updated?

It looks like I should update `README.V1.md`, but I didn't see a corresponding update in the reference change. Also happy to follow-up here.
