### ISSUE TITLE
Get test positive / negative counts for counties.

### ISSUE THREAD

**Issue by mikelehen** [covid-projections/covid-data-model#327]
We should be able to get case counts for some counties, but it looks like right now we don't.

E.g. WA [reports](https://www.doh.wa.gov/emergencies/coronavirus) case counts for all counties, but if I look up King County (fips 53033), we have no data:

```
$ curl -s https://data.covidactnow.org/snapshot/153/us/counties/53033.OBSERVED_INTERVENTION.json | python -mjson.tool | grep Tests

        "cumulativePositiveTests": null,
        "cumulativeNegativeTests": null,
```

We should figure out where we can get the data and then plumb it through.

**Comment by igorkofman** [comment]
Data is available here:
https://github.com/covid-projections/covid-data-public/blob/master/data/cases-cds/timeseries.csv

Unfortunately it is not reported / available for WA.  But is for some counties

**Comment by mikelehen** [comment]
Yeah, my example was bad (sorry!).  It looks like Washington is only reporting positive cases, not negative. 😞
