### ISSUE TITLE
Gaps in Rt data for many states.

### ISSUE THREAD

**Issue by mikelehen** [covid-projections/covid-data-model#340]
E.g. see:
https://staging.covidactnow.org/us/wa
https://staging.covidactnow.org/us/mt

![image](https://user-images.githubusercontent.com/206364/80550963-ad02a780-8976-11ea-8252-1a152afa1891.png)

I'd say almost half the states have a gap.  It's usually a single gap for a single day.  Though WA has two gaps: https://staging.covidactnow.org/us/wa. And AR has a 2-day gap: https://staging.covidactnow.org/us/ar

**Comment by BrettBoval** [comment]
States have known reporting gaps. We've improved interpolations and no longer surface these gaps to the front-end.
