### ISSUE TITLE
Static intervention projections have bad starting points for cumulativeInfected / cumulativeDeaths

### ISSUE THREAD

**Issue by mikelehen** [covid-projections/covid-data-model#347]
We currently show projected hospitalizations with the inference projection, compared to the static "no action" projection:
![image](https://user-images.githubusercontent.com/206364/80574322-777dae80-89b6-11ea-88d3-d8c52a9c15d0.png)

The Phase 3 UX mocks called for extending this to be able to toggle between hospitalizations and cumulative infected or cumulative deaths.  But the data is problematic:
![image](https://user-images.githubusercontent.com/206364/80574229-4f8e4b00-89b6-11ea-83e4-4bcf3e55c397.png)

If you look at the data in:
* https://data.covidactnow.org/snapshot/178/us/states/WA.NO_INTERVENTION.timeseries.json
* https://data.covidactnow.org/snapshot/178/us/states/WA.OBSERVED_INTERVENTION.timeseries.json

You'll see that they don't agree on how many cumulative infected or deaths we should have today (2020-04-29).

```
        {
            "date": "2020-04-29",
            ...
            "cumulativeDeaths": 763,
            "cumulativeInfected": 8273,
        },
```

vs

```
        {
            "date": "2020-04-29",
            ...
            "cumulativeDeaths": 1574,
            "cumulativeInfected": 458544,
        },
```

NO_INTERVENTION says we have 8273 infected.  OBSERVED_INTERVENTION says we have 458,544.

This makes it impossible to show them on the same chart.  cumulativeDeaths has the same problem.

**Comment by BrettBoval** [comment]
This specific use case is stale and no longer in scope.
