### ISSUE TITLE
turn notebook into voila app

### ISSUE THREAD

**Issue by osacn** [covid-projections/covid-data-model#4]
https://blog.jupyter.org/and-voil%C3%A0-f6a2c08a4a93

**Comment by jredding** [comment]
Once the notebook is up and running with interact + charts - this will be our goal. 

Dependent on #5

**Comment by davidstadem** [comment]
Looking into this....

What parameters are most important?
- R0
- HOSPITALIZATION_RATE 
- HOSPITALIZED_CASES_REQUIRING_ICU_CARE

**Comment by davidstrauss** [comment]
Closing, as our real-time modeling situation is considerably different now in ways that preclude just launching the notebook for interaction.
