### ISSUE TITLE
validate.py fails if results/test doesn't already exist.

### ISSUE THREAD

**Issue by mikelehen** [covid-projections/covid-data-model#47]
$ python validate.py -d ~/src/covid-data-public                                                                                                                            
Traceback (most recent call last):
  File "validate.py", line 64, in <module>
    clear_result_dir(build_params.OUTPUT_DIR)
  File "validate.py", line 25, in clear_result_dir
    for f in os.listdir(result_dir):
FileNotFoundError: [Errno 2] No such file or directory: 'results/test'

**Comment by mikelehen** [comment]
cc/ @gsoltis

**Comment by gsoltis** [comment]
Looks like `run.py` also fails in that scenario, once `validate.py` is fixed :(

I'll see if I can quick-fix that too

**Comment by davidstrauss** [comment]
Shouldn't that folder be auto-created by the readme I put into it?

**Comment by davidstrauss** [comment]
Looks like the readmes to generate the folders got dropped at some point in the past 48 hours. I'm happy to have them generated on-demand, though.
