### ISSUE TITLE
Testing -automated and smoke tests

### ISSUE THREAD

**Issue by jredding** [covid-projections/covid-data-model#7]
We need to think about basic testing within our scripts to ensure we are creating everything correctly. A few items we can test

- Integrity of input files in the dataset 
- State count of output .json file 
- size of the .json files (i.e. not null) 
- date span (not dropping dates) 

let's start with some basic smoke tests (ex. ensuring 1+1 per model .json for each state)

**Comment by ghop02** [comment]
There are a few areas I would like to address, but aren't in this PR:
 - Adding a linting github action (my guess is that we're going to want to be fairly loose with the rules)
 - Automatic code formatting - In other projects, I use a git commit hook to run `black`, but there might be a way to do it with github actions? Though I don't feel totally comfortable with automatic changes of that nature.
 - More than one test :)
 - More standardized environment setup instructions.  I personally ❤️pyenv + pyenv-virtualenv, though recognize that people run into issues with it.  Having everyone on the same python version (or in a set of python versions) reduces one more variable when debugging.
 - Should the cvoid_data_model be a proper python package? Not quite sure - I lean towards yes, but that probably depends a lot more on how/where it is used.
