### ISSUE TITLE
Make dates returned by the API ISO 8601 compliant

### ISSUE THREAD

**Issue by rodrigoescobar** [covid-projections/covid-data-model#816]
The date returned by the endpoint is not ISO 8601 compliant which makes it inconveniently difficult for clients to use relative dates with the information provided.

**Comment by ghop02** [comment]
Hi Rodrigo, I believe the date is a compatible ISO 8601 date. While it is not a datetime, it is a [date](https://www.w3.org/TR/NOTE-datetime) specified in YYYY-MM-DD format.  

Are you seeing a different value?

**Comment by rodrigoescobar** [comment]
I'm terribly sorry. That's what I meant. I meant to ask for it to be datetime compliant.

**Comment by ghop02** [comment]
I think we probably won't be changing the date format for now as it would be a breaking change for most consumers.

Though I'm happy to help find an easy way to parse that date object.  What language are you using?

**Comment by rodrigoescobar** [comment]
I understand. And thanks for the offer but that's okay :)
I already had a solution on which I was taking some assumptions. I asked just for the sense of having a down to the minute accurate information about when the data was published 

Keep up the good work.
