### ISSUE TITLE
Decide on Staffed vs. Licensed Beds

### ISSUE THREAD

**Issue by davidstrauss** [covid-projections/covid-data-model#84]
Most counties seem to have more licensed beds than staffed ones, but quite a few have the inverse. We should decide on which we rely on, or some combination thereof.

We're currently using licensed beds. Theoretically, that should include all beds that are allowed to operate (should the staffing materialize), but the data don't work that way in practice.

**Comment by asciimike** [comment]
I think we care about:
 - if licensed > staffed: staffed
 - if staffed > licensed: licensed

Which I think ends up being `min(licensed, staffed)`.

Basically: assume we can't staff beds immediately (doctors/nurses aren't geographically fungible), and assume that an excess of staff can't fix lack of beds immediately (we'd have to build more bed capacity).

This is the most pessimistic case, but also the one that makes the most reasonable assumptions IMO.

**Comment by davidstrauss** [comment]
I was going to propose the opposite (using max) or just switching to staffed, which seem to have more complete numbers for things like VA facilities.

Licensed woefully undercounts real capacity in a number of cases we've investigated.

**Comment by davidstrauss** [comment]
Here's the detail (pre-aggregation) from a county Michael mentioned had a disparity:
![Uploading Screenshot from 2020-04-01 22-32-16.png…]()

Here is a case where counties in Virginia have implausibly low capacity as measured by licensed beds:
![image (3)](https://user-images.githubusercontent.com/113350/78214471-2edfdd80-746a-11ea-969f-a96c7bb87f30.png)

**Comment by asciimike** [comment]
I sent over some better data that we can try. Potentially we take the MAX of those data sets then apply some algorithm.

**Comment by ghop02** [comment]
#85 Takes the max of those for right now
