### ISSUE TITLE
Combine mobility data?

### ISSUE THREAD

**Issue by MilesCranmer** [covid-projections/covid-data-model#96]
Hi all,

Fantastic work!! This model is awesome. 

I was wondering if you have considered using mobility data to inform whether a region is strictly or poorly complying with shelther-at-home orders? 

The data used in this NYT article: https://www.nytimes.com/interactive/2020/04/02/us/coronavirus-social-distancing.html is free and can be found here: https://www.cuebiq.com/visitation-insights-covid19/

It looks like they provide a county-by-county estimate of the change in mobility over time. I presume a small change in mobility since the order was enacted means there is poor compliance. 

Cheers,
Miles

**Comment by davidstrauss** [comment]
This is a relevant pull request, though with Google's data: #105
